// NAME MUST BE THE SAME USED IN ./l2d.json
// IF CHARACTER HAVE BEEN ADDED AFTER OVERZONE (18th may 2023) YOU MUST SAY IT IN l2d.json WITH SPINE VERSION 4.1
// CHECK BLANC, NOIR, OR RUPEE SKIN FOR EXAMPLE
const RELEASED_UNITS = [
    'Ade',
    'Admi',
    'Aki Hayakawa',
    'Alice',
    'Alice Sweet Home',
    'Anne: Miracle Fairy', 
    'Andersen',
    'Andersen Soaked',
    'Anis', 
    'Anchor',
    'Angelina',
    'Aria', 
    'Beatrice',
    'Belorta',
    'Biscuit',
    'Blanc',
    'Bolt',
    'Bolt Junior',
    'Booboo',
    'Brid',
    'Brid Model Worker',
    'Bridget', 
    'Burningum',
    // 'c350',
    'Cecil',
    'Centi',
    'Centi Supreme Holiday',
    'Cocoa',
    'Collection Robot',
    'Crow',
    'D',
    'Delta',
    'Denji',
    'Denji Chainsaw Man', 
    'Diesel',
    'Diesel Black Sunday',
    'Doban',
    'Dolla',
    'Dolla Dark Rose',
    'Dorothy',
    'Drake',
    'E.H.',
    'Ember', 
    'Emma',
    'Emma Color Me Red',
    'Enikk',
    'Ein',
    'Einkk',
    'Epinel', 
    'Espinel', 
    'Ether', 
    'Eunhwa', 
    'Exia',
    'Exia Join The Nerds',
    'Faceless Man',
    'Faceless NPC 1',
    'Faceless NPC 2',
    'Faceless NPC 3',
    'Faceless NPC 4',
    'Faceless NPC 5',
    'Faceless NPC 6',
    'Faceless NPC 7',
    'Faceless NPC 8',
    'Faceless NPC 9',
    'Faceless Woman',
    'Folkwang',
    'Frima', 
    'Guillotine',
    'Guilty', 
    'Harran',
    'Harran Story',
    'Helm',
    'Helm Chandelier',
    'Himeno',
    'Hologram',
    'iDoll Flower', 
    'iDoll Ocean', 
    'iDoll Sun',
    'Ingrid', 
    'Isabel',
    'Jackal',
    'Johan',
    'Joseph',
    'Julia', 
    'Julia Mild Nocturne',
    'K',
    'Laplace',
    'Liberalio',
    'Liberty', 
    'Liter',
    'Lucilla', 
    'Ludmilla',
    'Maiden',
    'Maiden Covert Nurse',
    'Makima',
    'Makima Coat Off',
    'Mana',
    'Marian',
    'Mary',
    'Mass Produced Blue',
    'Mass Produced Orange',
    'Mass Produced Green',
    'Mass Produced Purple',
    'Mass Produced White',
    'Mast',
    'Max',
    'Maxine', 
    'Maxwell',
    'Maxwell Mechanic White',
    'Mica', 
    'Mihara',
    'Milk',
    'Milk Extreme Fighter',
    'Miranda',
    'Modernia', 
    'Moran',
    'Mustang',
    'N102', 
    'Neon',
    'Neon Blind Bullet',
    'Nero',
    'Neve', 
    'Nihilister',
    'Nihilister Story',
    'Noah', 
    'Noir',
    'Noise',
    'Noise Cherry Blossom Stage',
    'Novel',
    'Novel Penguin Holmes',
    'Papillon',
    'Pepper',
    'Pinne',
    'Poli',
    'Poli Sweet Holic',
    'Power',
    'Privaty',
    'Privaty Government Grunt',
    'Product 08', 
    'Product 12', 
    'Product 23',
    'Quency', 
    'Rapi', 
    'Rapi_old', 
    'Rapi White Promise',
    'Rapunzel',
    'Raven',
    'Rei',
    'Rian',
    'Rosanna',
    'Rouge',
    'Rumani',
    'Rupee', 
    'Rupee Rabbit Deluxe',
    'Rupee: Winter Shopper',
    'Sakura',
    'Scarlet',
    'Shifty',
    'Shifty_old',
    'Signal',
    'Signal Dramatic Chocolate',
    'Sin', 
    'Snow White', 
    'Soda',
    'Soldier EG', 
    'Soldier FA', 
    'Soldier OW', 
    'Soline', 
    'Sugar',
    'Sugar Hard-Boiled',
    'Syuen',
    'Vesti',
    'Volume', 
    'Viper',
    'Viper Toxic Rabbit',
    'Yan', 
    'Yin',
    'Yulha', 
    'Yuni',
    'Yuni Pretty In Pink',
    'Zwei'
]
