const RELEASED_UNITS = [
    'Admi', 
    'Alice', 
    'Andersen',
    'Anis', 
    'Aria', 
    'Belorta', 
    'Brid', 
    'Bridget', 
    'Centi', 
    'Crow', 
    'Delta', 
    'Diesel', 
    'Dolla',
    'Drake', 
    'Ember', 
    'Emma', 
    'Enikk',
    'Epinel', 
    'Espinel', 
    'Ether', 
    'Eunhwa', 
    'Exia', 
    'Folkwang',
    'Frima', 
    'Guillotine', 
    'Harran',
    'Helm',
    'iDoll Flower', 
    'iDoll Ocean', 
    'iDoll Sun',
    'Ingrid', 
    'Julia', 
    'Liberty', 
    'Liter',
    'Lucilla', 
    'Ludmilla',
    'Maiden',
    // 'Marian',
    'Mary', 
    'Maxine', 
    'Maxwell', 
    'Mica', 
    'Mihara',
    'Milk', 
    'Miranda', 
    'Mustang',
    'N102', 
    'Neon', 
    'Noah', 
    'Noise', 
    'Novel',
    'Pepper',
    'Poli',
    'Privaty', 
    'Product 08', 
    'Product 12', 
    'Product 23', 
    'Rapi', 
    'Rapi_old', 
    'Rapunzel',
    'Raven', 
    'Scarlet',
    'Shifty',
    'Shifty_old',
    'Signal', 
    'Snow White', 
    'Soldier EG', 
    'Soldier FA', 
    'Soldier OW', 
    'Soline', 
    'Sugar', 
    'Syuen',
    'Vesti',
    'Volume', 
    'Yan', 
    'Yin',
    'Yulha', 
    'Yuni', 
]
